# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleSignin_MiniTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


pod 'GoogleSignIn'
pod 'Mapbox-iOS-SDK'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Alamofire'


end
